language: node_js

node_js:
- "lts/*"

os:
- linux
- osx

cache: npm

before_install:
  - npm i -g npm@latest

install:
- npm install

script:
- npm run lint
- npm run style

deploy:
  provider: lambda
  function_name: ''
  region: 'eu-west-1'

notifications:
  email:
    on_success: never
    on_failure: always