language: node_js

node_js:
- "lts/*"

os:
- linux
- osx
- windows

deploy_service_job: &TEST_LINT
  cache:
    - node_modules
  
  before_install:
    - npm i -g npm@latest
  
  install:
    - npm install
  
  script:
    - npm run lint
    - npm run style

deploy_lambda: &DEPLOY_LAMBDA
  cache:
    directories:
      - node_modules
      - ${PATH}/node_modules
  
  install:
    - npm install -g serverless
    - travis_retry npm install
    - cd ${PATH}
    - travis_retry npm install
    - cd -
  
  script:
    - cd ${path}
    - serverless deploy -d ${TRAVIS_BRANCH}
    - cd -

environments:
  - &PRODUCTION_ENV
    - AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_PRODUCTION}"
    - AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_PRODUCTION}"

  - &DEVELOPMENT_ENV
    - AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_DEVELOPMENT}"
    - AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_DEVELOPMENT}"

jobs:
  include:
    - <<: &TEST_LINT
      name: "Run script lint, prettier.."
    - <<: &DEPLOY_LAMBDA
      name: "Deploy specific lambde in dev stage"
      if: 
      env:
        - PATH=""
        - *DEVELOPMENT_ENV

notifications:
  email:
    on_success: never
    on_failure: always