language: node_js

node_js:
- "lts/*"

branches:
  only:
    - master
    - dev
    
jobs:
  include:
    # - stage: Lint
    #   cache:
    #     directories:
    #       - "node_modules"
      
    #   before_install:
    #     - npm i -g npm@latest
      
    #   install:
    #     - npm install
      
    #   script:
    #     - npm run lint
    #     - npm run style
    - stage: Deploy
      if: type = pull_request AND branch = dev
      cache:
        directories:
          - node_modules
          - lambdas/${TRAVIS_PULL_REQUEST_BRANCH}/node_modules
      
      install:
        - npm install -g serverless
        - travis_retry npm install
        - cd lambdas/${TRAVIS_PULL_REQUEST_BRANCH}
        - travis_retry npm install
        - cd -
      
      script:
        - cd lambdas/${TRAVIS_PULL_REQUEST_BRANCH}
        - serverless deploy -s ${TRAVIS_BRANCH}
        - cd -

notifications:
  email:
    on_success: never
    on_failure: always