service: loginLambda

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom: 
  dotenv:
    basePath: ../../
  serverless-offline:
    useDocker: true
    corsAllowHeaders: 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'
    corsExposedHeaders: 'WWW-Authenticate,Server-Authorization,Access-Control-Allow-Origin,Content-Type'
    corsDisallowCredentials: false
    printOutput: true
    apiKey: ${env:API_KEY_DEV}
  apiKey:
    dev: ${env:API_KEY_DEV}
    prod: ${env:API_KEY_PROD}

provider: 
  name: aws
  runtime: nodejs12.x
  apiName: bizzy-api
  stackName: loginLambda
  region: ${opt:region, 'eu-west-1'}
  versionFunctions: false
  endpointType: REGIONAL
  apiGateway:
    restApiId: ${env:REST_API_ID}
    restApiRootResourceId: ${env:REST_API_RESSOURCE_ID}
    apiKeySourceType: HEADER

package:
  include:
    - ./
    - ../../.env
  exclude:
    - .serverless-offline
    - package-lock.json

functions:
  login:
    handler: lambda.handler
    timeout: 3
    name: ${opt:stage, self:provider.stage, 'dev'}-login
    memorySize: 128
    layers:
      - arn:aws:lambda:eu-west-1:431852575624:layer:dependencies:2
    events:
      - http:
          path: /login
          method: post
          cors:
            headers: '*'
          private: true