service: bizzyLayers

provider:
  name: aws
  region: eu-west-1
  stage: ${opt:stage, 'dev'}

package:
  exclude:
    - package-lock.json

layers:
  bizzyLayers:
    path: ./
    description: All dependencies share by the diferents services
    compatibleRuntimes:
      - nodejs12.x
    retain: true