service: Home

provider: 
  - ${file(../../serverless.common.yml):provider}

package: ${file(../../serverless.common.yml):package}

plugins: ${file(../../serverless.common.yml):plugins}

custom: ${file(../../serverless.common.yml):custom}

apiGateway: ${file(../../serverless.common.yml):apiGateway}

functions:
  Home:
    name: home-${self:custom.stage}
    handler: lambda.handler
    description: Return all routes availables for this API.
    timeout: 3
    memorySize: 128
    layers:
      - arn:aws:lambda:eu-west-1:431852575624:layer:LyrResponse:1
    events:
      - http:
        path: /test
        method: GET
        cors: true