service: homeLambda

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom: ${file(../../serverless.common.yml):custom}

provide: ${file(../../serverless.common.yml):provider}

function:
  home:
    handler: lambda.handler
    timeout: 3
    memorySize: 128
    layers:
      - arn:aws:lambda:eu-west-1:431852575624:layer:dependencies:2
    events:
      - http:
          path: /
          method: get
          cors:
            headers: '*'
          private: true