service: homeLambda

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom: 
  dotenv:
    basePath: ../../
  serverless-offline:
    useDocker: true
    corsAllowHeaders: 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'
    corsExposedHeaders: 'WWW-Authenticate,Server-Authorization,Access-Control-Allow-Origin,Content-Type'
    corsDisallowCredentials: false
    printOutput: true
    apiKey: ${env:API_KEY_DEV}
  apiKey:
    dev: ${env:API_KEY_DEV}
    prod: ${env:API_KEY_PROD}

provider: 
  name: aws
  runtime: nodejs12.x
  apiName: bizzy-api
  stackName: homeLambda
  region: ${opt:region, 'eu-west-1'}
  versionFunctions: false
  endpointType: REGIONAL
  apiGateway:
    restApiId: gacc5r6i15
    restApiRootResourceId: a3e1htzhzd
    apiKeySourceType: HEADER
  apiKeys:
    - name: API_KEY
      value: ${self:custom.apiKey.${opt:stage, 'dev'}}

package:
  include:
    - ./

functions:
  home:
    handler: lambda.handler
    timeout: 3
    memorySize: 128
    layers:
      - arn:aws:lambda:eu-west-1:431852575624:layer:dependencies:2
    events:
      - http:
          path: /
          method: get
          cors:
            headers: '*'
          private: true