service: frontauth

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

package:
  individually: true
  include:
    - ./.env

functions:
  frontAuth:
    name: frontauth-${opt:stage}-frontAuth
    handler: index.handler
    description: Secure front-end in dev mode with authentication
    memorySize: 128
    timeout: 5